### ISSUE TITLE
ranking info?

### ISSUE THREAD

**Issue by McCloudFace** [rpt09-scully/reviews-service#7]
@ryanbrennan12 - Hey. Is there an [example response](https://github.com/rpt09-scully/reviews-service/blob/master/example-data.json) for the `get/{trailId}/trailRank` end point? I see it's just a string, but wondering what the res object looks like?

**Comment by ryanbrennan12** [comment]
It uses a getRanking function that adds up all the stars for the corresponding trails.  The output looks like `{ '1': 23,
  '2': 33,
  '3': 11,
  '4': 12,
  '5': 28,
  '6': 21,
  '7': 25,
  '8': 29,
  '9': 42,
  '10': 15,
  '11': 22,
  '12': 18,
  '13': 25,
  '14': 31,
  '15': 21,
  '16': 11,
  '17': 28,
  '18': 19,
  '19': 25,
  '20': 30 }`
